# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake Ubuntu 22.04 build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: sudo apt-get install clang clang-format clang-tidy gcc-10 gcovr build-essential googletest libgtest-dev libgmock-dev libspdlog-dev qtbase5-dev libqt5bluetooth5 qtconnectivity5-dev

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      run: cmake -S ${{github.workspace}}/Source -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config Debug

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      run: ctest -C Debug

    - name: Check Test Coverage
      uses: threeal/gcovr-action@v1.1.0
      with:
        html-out: coverage.html
        html-details: true
        html-title: My Project Test Coverage Report
        html-theme: green

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: /usr/bin/gcovr/coverage.html